import Layout from "../../components/Layout"
import Head from "next/head"
import { Heading, Box } from "@chakra-ui/react"
import Colour from "../../color/napalearncolor"
import GuitarIns from "../../components/GuitarIns"

export default function Guitar() {

    let line = {
        width: '1000',
        height: '2px',
        bgColor: Colour.Darkblue,
        marginTop: '12px',
        marginBottom: '12px',
    }

    return (
        <div>
            <Head>
                <title>Nap A Learn Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/pro.ico" />
            </Head>
            <Layout> {/* show guitar instrument*/}
                <div className="p-4 mt-1">
                    <Heading size='2xl'>Guitar Therapy</Heading>
                    <Box sx={line}></Box>
                    <GuitarIns />
                </div>
            </Layout>
        </div>

    )
}