import Layout from "../../components/Layout"
import Head from "next/head"
import { Center, Box, Wrap, WrapItem } from "@chakra-ui/react"
import Colour from "../../color/napalearncolor"
import MusicMenu from "../../components/MusicMenu"

export default function MusicInstrument() {

    let boxMusic = {
        backgroundColor: 'White',
        width: '1000px',
        marginTop: '10px',
        borderRadius: '10px',
        boxShadow: 'md',
    }
    let menu = {
        color: Colour.Darkblue,
        fontSize: '36px',
        fontWeight: 'bold',
        paddingLeft: 30,
        paddingRight: 30,
        paddingTop: 15,
    }

    return (
        <div>
            <Head>
                <title>Nap A Learn Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/pro.ico" />
            </Head>
            <Layout>
                <div className="p-4 mt-10">
                    <Center>
                        <Box sx={boxMusic}>
                            <Box sx={menu}> {/* show music instrument menu*/}
                                Select music instrument
                            </Box>
                            <Wrap marginTop={50} marginBottom={100} marginRight={50} marginLeft={50} spacing={200} justify='center'>
                                <WrapItem>
                                    <MusicMenu src='/image/piano.png' link='/musictherapy/pianotherapy' />
                                </WrapItem>
                                <WrapItem>
                                    <MusicMenu src='/image/guitar (1).png' link='/musictherapy/guitartherapy' />
                                </WrapItem>
                            </Wrap>
                        </Box>
                    </Center>

                    <Center>
                        <Box sx={boxMusic}>
                            <Box sx={menu}>
                                Select sound therapy {/* show sound therapy menu*/}
                            </Box>
                            <Wrap marginTop={50} marginBottom={100} marginRight={50} marginLeft={50} spacing={150} justify='center'>
                                <WrapItem>
                                    <MusicMenu src='/image/music.png' link='/musictherapy/soundtherapy' />
                                </WrapItem>
                            </Wrap>
                        </Box>
                    </Center>
                </div>
            </Layout>
        </div>
    )
}