import Layout from "../../components/Layout"
import Head from "next/head"
import { Center, Heading, Box, Text } from "@chakra-ui/react"
import Colour from "../../color/napalearncolor"
import SoundMenu from "../../components/SoundMenu"

export default function SoundTherapy() {

    let line = {
        width: '900',
        height: '2px',
        bgColor: Colour.Darkblue,
        marginTop: '12px',
        marginBottom: '12px',
        marginRight: '30px',
    }
    let menuBox = {
        backgroundColor: 'White',
        width: '1000px',
        marginTop: '10px',
        borderRadius: '10px',
        boxShadow: 'md',
        paddingLeft: '30px',
        paddingBottom: '30px',
    }
    let textStyle = {
        color: Colour.Darkblue,
        fontSize: '36px',
        fontWeight: 'bold',
        paddingRight: '30px',
        paddingTop: '15px',
    }

    return (
        <div>
            <Head>
                <title>Nap A Learn Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/pro.ico" />
            </Head>
            <Layout>
                <div className="p-4 mt-1">
                    <Heading size='2xl'>Sound Therapy</Heading>
                    <Box sx={line}></Box>
                </div>
                <Center>
                    <Box sx={menuBox}>
                        <Text sx={textStyle}>
                            Select sound therapy
                        </Text>
                        <Box sx={line}></Box> {/* show menu select sound*/}
                        <SoundMenu link='/musictherapy/rain' title='Rain Sound' />
                        <SoundMenu link='/musictherapy/fireplace' title='Fireplace Sound' />
                        <SoundMenu link='/musictherapy/waterfall' title='Waterfall Sound' />
                        <SoundMenu link='/musictherapy/sleep' title='Deep sleeping music' />
                        <SoundMenu link='/musictherapy/productivity' title='Productivity music' />
                    </Box>
                </Center>
            </Layout>
        </div>
    )
}

