import Head from "next/head";
import { Heading, Box, Wrap } from '@chakra-ui/react';
import Layout from "../../components/Layout";
import Colour from "../../color/napalearncolor";
import BoxLearningProfessional from '../../components/BoxLearningProfessional';

export default () => {
      let line = {
            bgColor: Colour.Darkblue,
            width: '100%',
            marginTop: '12px',
            height: '2px',
      }

      return (
            <div>
                  <Head>
                        <title>Nap A Learn Website</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/pro.ico" />
                  </Head>
                  <Layout>
                        <div className="p-4 mt-1">
                              <Heading color='#3E3C6E' size='2xl'>Learning Materials</Heading>
                              <Box sx={line}></Box> {/* show article menu and material menu */}
                              <Wrap align='center' justify='center' spacingX='50px' spacingY='12px'>
                                    <BoxLearningProfessional link={`/learning/article`} image='/image/articlelearning.jpg' headding='Article' text='Read more to improve youself' />
                                    <BoxLearningProfessional link={`/learning/material`} image='/image/material.png' headding='Material' text='online playground for you' />
                              </Wrap>
                        </div>
                  </Layout>
            </div>
      );
}