import { Box, Heading, useToast, Wrap, WrapItem } from '@chakra-ui/react';
import Head from "next/head";
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Colour from "../../color/napalearncolor";
import BoxSelect from '../../components/BoxSelect';
import Layout from "../../components/Layout";

export default () => {

    let line = {
        width: '100%',
        marginTop: '12px',
        height: '2px',
        bgColor: Colour.Darkblue,
        marginBottom: '12px',
    }

    const router = useRouter()
    const toast = useToast()

    // check user role
    useEffect(() => {
        const kickOut = () => {
            sessionStorage.clear()
            router.push('/')
            toast({
                title: 'Cannot access the website',
                description: "Please log in to use the website",
                status: 'error',
                duration: 5000
            })
        }
        if (sessionStorage.getItem('userrole') == 1) {
            kickOut()
        }
    }, [])

    return (
        <div className="">
            <Head>
                <title>Nap A Learn Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/pro.ico" />
            </Head>
            <Layout>
                <div className="p-4 mt-1">
                    <Heading size='2xl'>[Admin] Manage</Heading>
                    <Box sx={line}></Box>
                    <Wrap align='center' justify='center' spacingX='50px' spacingY='12px'>
                        <WrapItem> {/* select menu manage */}
                            <BoxSelect Header='Learning Materials' Link1='/manage/learnarticle' Topic1='Article'
                                Link2='/manage/learnmaterial' Topic2='Materials' Icon='2' />
                        </WrapItem>
                        <WrapItem>
                            <BoxSelect Header='Professional Skills' Link1='/manage/professarticle' Topic1='Article'
                                Link2='/manage/professmaterial' Topic2='Materials' Icon='1' />
                        </WrapItem>
                    </Wrap>
                </div>
            </Layout>
        </div>
    );
}