import {
  Accordion, AccordionButton, AccordionIcon, AccordionItem, AccordionPanel, Box, Button, Flex, Heading, Tab,
  TabList, TabPanel, TabPanels, Tabs, Text, VStack
} from '@chakra-ui/react';
import axios from 'axios';
import Head from "next/head";
import NextLink from "next/link";
import Colour from "../../../color/napalearncolor";
import BoxAllSkillI from '../../../components/BoxAllSkillI';
import BoxSummary from "../../../components/BoxSummaryI";
import BoxNoData from '../../../components/BoxNoData';
import Layout from "../../../components/Layout";
import url from '../../url';
import { useEffect, useState } from 'react'
import { Router, useRouter } from 'next/router';
import Loading from '../../../components/SubLoading';

export default () => {

  const [loading, setLoading] = useState(false);

  let line = {
    width: '100%',
    marginTop: '12px',
    height: '2px',
    bgColor: Colour.Darkblue
  }
  let boxSelect = {
    padding: '8px',
    height: '40px',
    marginLeft: '20px',
    marginTop: '24px',
  }
  let boxResult = {
    bgColor: Colour.White,
    width: '80%',
    padding: '12px',
    paddingTop: '20px',
    paddingLeft: '20px',
    marginLeft: '20px',
    marginRight: '20px',
    marginTop: '32px',
    marginBottom: '32px',
  }
  let boxButton = {
    bgColor: Colour.White,
    width: '40%',
    padding: '12px',
    marginTop: '24px',
    marginBottom: '24px',
  }
  let boxData = {
    width: '90%',
    marginTop: '32px',
  }
  let boxData1 = {
    bgColor: Colour.White,
  }

  const router = useRouter()
  const userID = router.query.usernumberID
  console.log(userID)
  const [result, setResult] = useState([])

  // fetch data result from question 1 when query is usernumberID
  const fetchData = async () => {
    let result = await axios.get(`${url}/api/Result/getResult1/${userID}`, {
    })
    setResult(result.data)
    console.log(result)
    setLoading(false)
  }

  useEffect(() => {
    setLoading(true)
    if (userID) { fetchData() }
  }, [])

  // fetch data result each question to evaluate the skill list
  let response = Object.values(result).map(value => value)
  let point = 0
  let apoint = 0
  let bpoint = 0
  let cpoint = 0
  let skill = []
  let pointskills = 0
  let apointskills = 0
  let bpointskills = 0

  for (let i = 0; i <= 19; i++) {
    point = point + parseInt(response[i])
  }
  for (let i = 20; i <= 39; i++) {
    apoint = apoint + parseInt(response[i])
  }
  for (let i = 40; i <= 59; i++) {
    bpoint = bpoint + parseInt(response[i])
  }
  for (let i = 60; i <= 79; i++) {
    cpoint = cpoint + parseInt(response[i])
  }

  for (let i = 0; i <= 18; i += 2) {
    skill[i] = (parseInt(response[i]) + parseInt(response[i])) == 0 ? 0 : 1
    pointskills = pointskills + skill[i]
  }
  for (let i = 20; i <= 38; i += 2) {
    skill[i] = (parseInt(response[i]) + parseInt(response[i])) == 0 ? 0 : 1
    apointskills = apointskills + skill[i]
  }
  for (let i = 40; i <= 58; i += 2) {
    skill[i] = (parseInt(response[i]) + parseInt(response[i])) == 0 ? 0 : 1
    bpointskills = bpointskills + skill[i]
  }

  let check = (point) < 0 ? 1 : 0
  let passvalue = (pointskills) >= 8 ? 1 : 0
  let data = [
    { title: "ผ่าน", value: pointskills, color: "#97CF47" },
    { title: "ไม่ผ่าน", value: 10 - pointskills, color: "#FF7121" },
  ];

  let acheck = (apoint) < 0 ? 1 : 0
  let ause = (apoint) < 0 ? 0 : apoint
  let apassvalue = (apointskills) >= 8 ? 1 : 0
  let adata = [
    { title: "ผ่าน", value: apointskills, color: "#97CF47" },
    { title: "ไม่ผ่าน", value: 10 - apointskills, color: "#FF7121" },
  ];

  let bcheck = (bpoint) < 0 ? 1 : 0
  let buse = (bpoint) < 0 ? 0 : bpoint
  let bpassvalue = (bpointskills) >= 8 ? 1 : 0
  let bdata = [
    { title: "ผ่าน", value: bpointskills, color: "#97CF47" },
    { title: "ไม่ผ่าน", value: 10 - bpointskills, color: "#FF7121" },
  ];

  let cuse = (cpoint) < 0 ? 0 : cpoint

  return (
    <div className="">
      <Head>
        <title>Nap A Learn Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Layout>
        <Loading isLoading={loading} />
        <div className="p-4 mt-1">
          <Heading size='xl'>ผลการคัดกรองบุคคลที่มีความบกพร่องทางสติปัญญา</Heading>
          <Box sx={line}></Box> {/* check result if the test is not performed */}
          {(check) == 1 ?
            <Flex align="center" justify="center">
              <Box sx={boxResult} boxShadow='md' p='6' rounded='md' align="center" justify="center">
                <Box sx={boxButton}>
                  <Heading>ยังไม่ได้ทำการทดสอบ</Heading>
                </Box>
                <Box sx={boxButton} justify="center">
                  <NextLink href="/question/question1" passHref>
                    <Button width='100%' borderRadius='md' bg={Colour.FirstPink} color='White' size='lg'
                      _hover={{ bg: 'White', border: '2px solid', color: Colour.FirstPink }}>
                      Go to Questionnaire
                    </Button>
                  </NextLink>
                </Box>
              </Box>
            </Flex> :
            <Tabs variant='soft-rounded' colorScheme="pink">
              <Box sx={boxSelect}>
                <TabList>
                  <Tab _hover={{ bg: 'White', border: '2px solid', color: Colour.FirstPink }}>ผลการทดสอบปัจจุบัน</Tab>
                  <Tab _hover={{ bg: 'White', border: '2px solid', color: Colour.FirstPink }}>ผลการทดสอบย้อนหลัง 2 ครั้งล่าสุด</Tab>
                </TabList>
              </Box>
              <TabPanels>
                <TabPanel> {/* tab current result */}
                  <VStack spacing={8} align="center">
                    <BoxSummary point={point} pointbefore={ause} passvalue={passvalue} />
                    <BoxAllSkillI skill1={skill[0]} skill2={skill[2]} skill3={skill[4]} skill4={skill[6]} skill5={skill[8]}
                      skill6={skill[10]} skill7={skill[12]} skill8={skill[14]} skill9={skill[16]} skill10={skill[18]} data={data} />
                  </VStack>
                </TabPanel>
                <TabPanel> {/* tab two last result */}
                  <Flex justifyContent='center'>
                    <Box sx={boxData} align="center" >
                      <Accordion allowToggle>
                        <AccordionItem>
                          <h2>
                            <Box sx={boxData1}>
                              <AccordionButton>
                                <Box flex='1' textAlign='left'>
                                  {(result.adatetime) == -1 ? <Text>ไม่มีข้อมูลย้อนหลัง</Text> :
                                    <Text>ข้อมูลย้อนหลังวันที่ {(new Date(result.adatetime)).toLocaleString()}</Text>}
                                </Box>
                                <AccordionIcon />
                              </AccordionButton>
                            </Box>
                          </h2>
                          <AccordionPanel pb={4}>
                            {/* result olddata 1 */}
                            {(acheck) == 1 ?
                              <BoxNoData /> :
                              <VStack spacing={8} align="center">
                                <BoxSummary point={apoint} pointbefore={buse} passvalue={apassvalue} />
                                <BoxAllSkillI skill1={skill[20]} skill2={skill[22]} skill3={skill[24]} skill4={skill[26]} skill5={skill[28]}
                                  skill6={skill[30]} skill7={skill[32]} skill8={skill[34]} skill9={skill[36]} skill10={skill[38]} data={adata} />
                              </VStack>}
                          </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem>
                          <h2>
                            <Box sx={boxData1}>
                              <AccordionButton>
                                <Box flex='1' textAlign='left'>
                                  {(result.bdatetime) == -1 ? <Text>ไม่มีข้อมูลย้อนหลัง</Text> :
                                    <Text>ข้อมูลย้อนหลังวันที่ {(new Date(result.bdatetime)).toLocaleString()}</Text>}
                                </Box>
                                <AccordionIcon />
                              </AccordionButton>
                            </Box>
                          </h2>
                          <AccordionPanel>
                            {/* result olddata 2 */}
                            {(bcheck) == 1 ?
                              <BoxNoData /> :
                              <VStack spacing={8} align="center">
                                <BoxSummary point={bpoint} pointbefore={cuse} passvalue={bpassvalue} />
                                <BoxAllSkillI skill1={skill[40]} skill2={skill[42]} skill3={skill[44]} skill4={skill[46]} skill5={skill[48]}
                                  skill6={skill[50]} skill7={skill[52]} skill8={skill[54]} skill9={skill[56]} skill10={skill[58]} data={bdata} />
                              </VStack>}
                          </AccordionPanel>
                        </AccordionItem>
                      </Accordion>
                    </Box>
                  </Flex>
                </TabPanel>
              </TabPanels>
            </Tabs>
          }
        </div>
      </Layout>
    </div>
  );
}

