import Head from "next/head";
import { Heading, Box, Wrap } from '@chakra-ui/react';
import Layout from "../../components/Layout";
import Colour from "../../color/napalearncolor";
import BoxLearningProfessional from '../../components/BoxLearningProfessional';

export default function professionalusic() {
      let line = {
            bgColor: Colour.Darkblue,
            width: '100%',
            marginTop: '12px',
            height: '2px',
      }

      return (
            <div>
                  <Head>
                        <title>Nap A Learn Website</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/pro.ico" />
                  </Head>
                  <Layout>
                        <div className="p-4 mt-1">
                              <Heading color='#3E3C6E' size='2xl'>Professional Skills</Heading>
                              <Box sx={line}></Box> {/* select article or material */}
                              <Wrap align='center' justify='center' spacingX='50px' spacingY='12px'>
                                    <BoxLearningProfessional link={`/professional/article`} image='/image/article.jpg' headding='Article' text='Read for capable of stirring up fresh life endlessly' />
                                    <BoxLearningProfessional link={`/professional/workshop`} image='/image/workshop.jpg' headding='Work Shop' text='Find the hobby that you love to be career' />
                              </Wrap>
                        </div>
                  </Layout>
            </div>
      );
}
